server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ecole221-backend
  
  # Base de données H2 en mémoire par défaut pour un démarrage instantané
  datasource:
    url: jdbc:h2:mem:ecole221db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT Configurations customisées
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 heures
